<?php

/**
 * @file
 * Contains \Drupal\Core\Asset\Aggregate\JsAggregateAsset.
 */

namespace Drupal\Core\Asset\Aggregate;
use Drupal\Core\Asset\AssetInterface;
use Drupal\Core\Asset\JavascriptAssetInterface;
use Drupal\Core\Asset\Metadata\AssetMetadataBag;
use Drupal\Core\Asset\Metadata\JsMetadataBag;

/**
 * A Javascript asset that aggregates together multiple other Javascript assets.
 */
class JsAggregateAsset extends BaseAggregateAsset implements JavascriptAssetInterface {

  /**
   * {@inheritdoc}
   *
   * @throws \Drupal\Core\Asset\Exception\AssetTypeMismatchException
   */
  public function __construct(AssetMetadataBag $metadata, $assets = array(), $filters = array(), $sourceRoot = array()) {
    if (!$metadata instanceof JsMetadataBag) {
      throw new AssetTypeMismatchException('CSS aggregates require CSS metadata bags.');
    }

    parent::__construct($metadata, $assets, $filters, $sourceRoot); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  protected function ensureCorrectType(AssetInterface $asset) {
   if (!($asset instanceof StylesheetAssetInterface || $asset instanceof self)) {
      throw new AssetTypeMismatchException('CSS aggregates can only work with CSS assets.');
    }
  }
}